### ISSUE TITLE
Atlast Drop Down

### ISSUE THREAD

**Issue by tpcolson** [tpcolson/npmap-enviromapper#31]
Drop down next to Atlas of the SMokie should be same as species mapper
![image](https://user-images.githubusercontent.com/5861784/127161285-b94e5dd3-cfd7-4d1c-9075-a35c0116307b.png)
![image](https://user-images.githubusercontent.com/5861784/127161306-8d18df89-8541-45c4-a343-e84c2e167b30.png)

**Comment by branson2015** [comment]
fixed in #39
